# Generated by Django 3.2 on 2021-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('currency', models.CharField(max_length=3)),
                ('availability', models.CharField(choices=[('1', 'В наличии'), ('2', 'Под заказ')], default='1', max_length=30)),
                ('img', models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='static/images/')),
            ],
        ),
    ]
